### ISSUE TITLE
bluebird v3 support

### ISSUE THREAD

**Issue by focusaurus** [Janpot/pg-query-bluebird#2]
Thanks for this very handy module! Would you be willing to update to the latest bluebird and release a new version of pg-query-bluebird? I've seen an incompatibility with bluebird v3 leading to `TypeError: Cannot read property 'getOrCreate' of undefined` during the connection, which I believe is at least partially caused by an API change in bluebird's `promisify`. I think in `lib/index.js` you need something like this:

`var pgConnect = Promise.promisify(pg.connect, {context: pg});`

I forked and attempted to fix this, but I'm having trouble getting the tests passing with my proposed changes (I got them passing with the current master branch code). Before spinning my wheels too much understanding I figured I'd file and issue and see if you might be able to get things solved faster.

With my change, the unit tests were hitting this exception in case this gives you any clues:

```
TypeError: expecting an array or an iterable object but got [object Null]
    at /Users/plyons/projects/pg-query-bluebird/node_modules/pg/lib/pool.js:84:11
    at /Users/plyons/projects/pg-query-bluebird/node_modules/pg/node_modules/generic-pool/lib/generic-pool.js:281:11
    at /Users/plyons/projects/pg-query-bluebird/node_modules/pg/lib/pool.js:58:20
    at null.<anonymous> (/Users/plyons/projects/pg-query-bluebird/node_modules/pg/lib/client.js:149:7)
```

**Comment by focusaurus** [comment]
Actually, I think I figured it out. PR #3 submitted.

**Comment by vitaly-t** [comment]
@focusaurus do you know that [pg-promise](https://github.com/vitaly-t/pg-promise) works with Bluebird perfectly? In fact, it is the recommended promise library for it. See [promiseLib option](https://github.com/vitaly-t/pg-promise#promiselib).

**Comment by focusaurus** [comment]
Haven't seen that one. Will have a look. Thanks.

**Comment by Janpot** [comment]
@focusaurus I created this library because I like the `Promise.using` semantics in bluebird.
